# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_books_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
