# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-14 05:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20160712_1004'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='books',
            options={'verbose_name_plural': 'book'},
        ),
        migrations.RemoveField(
            model_name='books',
            name='slug',
        ),
    ]
